/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksSourceIdRouteImport } from './routes/books.$sourceId'
import { Route as CircularsIndexRouteImport } from './routes/circulars.index'
import { Route as CircularsSourceIdRouteImport } from './routes/circulars.$sourceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSourceIdRoute = BooksSourceIdRouteImport.update({
  id: '/books/$sourceId',
  path: '/books/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularsIndexRoute = CircularsIndexRouteImport.update({
  id: '/circulars/',
  path: '/circulars/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircularsSourceIdRoute = CircularsSourceIdRouteImport.update({
  id: '/circulars/$sourceId',
  path: '/circulars/$sourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/books/$sourceId': typeof BooksSourceIdRoute
  '/circulars/$sourceId': typeof CircularsSourceIdRoute
  '/circulars/': typeof CircularsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/books/$sourceId': typeof BooksSourceIdRoute
  '/circulars/$sourceId': typeof CircularsSourceIdRoute
  '/circulars': typeof CircularsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/books/$sourceId': typeof BooksSourceIdRoute
  '/circulars/$sourceId': typeof CircularsSourceIdRoute
  '/circulars/': typeof CircularsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/books/$sourceId' | '/circulars/$sourceId' | '/circulars/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/books/$sourceId' | '/circulars/$sourceId' | '/circulars'
  id:
    | '__root__'
    | '/'
    | '/books/$sourceId'
    | '/circulars/$sourceId'
    | '/circulars/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BooksSourceIdRoute: typeof BooksSourceIdRoute
  CircularsSourceIdRoute: typeof CircularsSourceIdRoute
  CircularsIndexRoute: typeof CircularsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$sourceId': {
      id: '/books/$sourceId'
      path: '/books/$sourceId'
      fullPath: '/books/$sourceId'
      preLoaderRoute: typeof BooksSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulars/': {
      id: '/circulars/'
      path: '/circulars'
      fullPath: '/circulars/'
      preLoaderRoute: typeof CircularsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circulars/$sourceId': {
      id: '/circulars/$sourceId'
      path: '/circulars/$sourceId'
      fullPath: '/circulars/$sourceId'
      preLoaderRoute: typeof CircularsSourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BooksSourceIdRoute: BooksSourceIdRoute,
  CircularsSourceIdRoute: CircularsSourceIdRoute,
  CircularsIndexRoute: CircularsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
